# Generated by Django 4.1.3 on 2023-04-17 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("nadooit_website", "0022_session_experiment_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="session_signals",
        ),
        migrations.AddField(
            model_name="session_signals",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="nadooit_website.session",
            ),
        ),
    ]
