# Generated by Django 4.1.2 on 2022-10-24 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("nadooit_hr", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeyManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_create_keys", models.BooleanField(default=False)),
                ("can_delete_keys", models.BooleanField(default=False)),
                ("can_update_keys", models.BooleanField(default=False)),
                ("can_create_key_managers", models.BooleanField(default=False)),
                ("can_delete_key_managers", models.BooleanField(default=False)),
                ("can_update_key_managers", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nadooit_hr.employee",
                    ),
                ),
            ],
        ),
    ]
