# Generated by Django 4.1.2 on 2022-10-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nadooit_key', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keymanager',
            name='key_managers_assigened_by_this_key_manager',
            field=models.ManyToManyField(blank=True, to='nadooit_key.keymanager'),
        ),
    ]
