# Generated by Django 4.0.7 on 2022-08-24 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nadooit_api_executions_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nadooitapikey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='developer',
            name='teams',
            field=models.ManyToManyField(related_name='developer_teams', to='nadooit_api_executions_system.team'),
        ),
        migrations.AddField(
            model_name='customerprogramexecution',
            name='customer_program_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nadooit_api_executions_system.customerprogram'),
        ),
        migrations.AddField(
            model_name='customerprogram',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nadooit_api_executions_system.customer'),
        ),
        migrations.AddField(
            model_name='customerprogram',
            name='program_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nadooit_api_executions_system.program'),
        ),
        migrations.AddField(
            model_name='customer',
            name='addresses',
            field=models.ManyToManyField(related_name='customer_addresses', to='nadooit_api_executions_system.address'),
        ),
    ]
