# Generated by Django 4.0.7 on 2022-08-24 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nadooit_api_executions_system', '0001_initial'),
        ('nadooit_crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprogram',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nadooit_crm.customer'),
        ),
        migrations.AddField(
            model_name='customerprogram',
            name='program_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nadooit_api_executions_system.program'),
        ),
    ]
