# Generated by Django 4.0.7 on 2022-08-25 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nadooit_api_executions_system', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprogram',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='customerprogram',
            name='program_id',
        ),
        migrations.RemoveField(
            model_name='customerprogramexecution',
            name='customer_program_id',
        ),
    ]
