# Generated by Django 4.0.7 on 2022-08-24 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nadooit_api_executions_system', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NadooitApiKey',
        ),
    ]
