# Generated by Django 4.0.7 on 2022-08-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nadooit_api_executions_system', '0004_customerprogramexecution_customer_program_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprogramexecution',
            name='program_time_saved',
        ),
        migrations.AddField(
            model_name='customerprogramexecution',
            name='program_time_saved_in_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
