# Generated by Django 4.0.7 on 2022-08-25 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nadooit_api_executions_system', '0005_remove_customerprogramexecution_program_time_saved_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Program',
        ),
    ]
