FROM python:3.10-slim-buster
LABEL maintainer="nadooit.de"

ENV PYTHONUNBUFFERED 1

COPY requirements-dev.txt /requirements.txt

RUN mkdir /app
COPY app/ /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    git \
    gcc \
    libc-dev \
    ffmpeg \
    default-libmysqlclient-dev \ 
    pkg-config
RUN unset https_proxy

RUN mkdir -p /vol/web/static/media
RUN mkdir -p /vol/web/static/static
RUN mkdir -p /home/django/.postgresql/

#OLD RUN adduser -D --disabled-password --no-create-home django
RUN adduser --disabled-password --gecos "" django

RUN chown -R django:django app/
RUN chown -R django:django /vol

RUN chmod -R 755 app/
RUN chmod -R 755 /vol/web
WORKDIR /app

EXPOSE 8000

RUN chown -R django:django /app
RUN chown -R django:django /home/django
RUN chmod 755 /home/django
RUN chmod 755 /app
USER django

RUN pip install --upgrade pip
RUN pip install --upgrade cython
RUN pip install -r /requirements.txt 

USER root

RUN apt-get purge -y --auto-remove \
    build-essential \
    curl \
    git \
    gcc \
    libc-dev \
    linux-headers-amd64

USER django