version: '3.3'
services:
  app:
    build:
      context: .
    restart: always
    environment:
      - 'DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}'
      - 'DJANGO_ALLOWED_HOSTS=${DOMAIN}'
      - 'COCKROACH_DB_HOST=${COCKROACH_DB_HOST}'
      - 'COCKROACH_DB_NAME=${COCKROACH_DB_NAME}'
      - 'COCKROACH_DB_PORT=${COCKROACH_DB_PORT}'
      - 'COCKROACH_DB_USER=${COCKROACH_DB_USER}'
      - 'COCKROACH_DB_PASSWORD=${COCKROACH_DB_PASSWORD}'
      - 'NADOOIT__API_KEY=${NADOOIT__API_KEY}'
      - 'NADOOIT__USER_CODE=${NADOOIT__USER_CODE}'
    volumes:
      - /home/django/.postgresql/:/home/django/.postgresql/ 
      - static_data:/vol/web/static
  proxy:
    build:
      context: ./docker/proxy
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'certbot-web:/vol/www'
      - 'proxy-dhparams:/vol/proxy'
      - 'certbot-certs:/etc/letsencrypt'
      - static_data:/vol/web/static
    environment:
      - 'DOMAIN=${DOMAIN}'
    depends_on:
      - app
  certbot:
    build:
      context: ./docker/certbot
    command: echo "Skipping certbot"
    environment:
      - 'EMAIL=${ACME_DEFAULT_EMAIL}'
      - 'DOMAIN=${DOMAIN}'
    volumes:
      - 'certbot-web:/vol/www'
      - 'certbot-certs:/etc/letsencrypt'
    depends_on:
      - proxy
volumes:
  certbot-web: null
  proxy-dhparams: null
  certbot-certs: null
  static_data: null
