version: '3.3'

networks:
  app_network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: >-
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver_plus 0.0.0.0:8000 --cert-file cert.cer --key-file key.pem --insecure"
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - ./data/web:/vol/web
    environment:
      - 'DJANGO_DEBUG=${DJANGO_DEBUG}'
      - 'OPENAI_API_KEY=${OPENAI_API_KEY}'
      - 'DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}'
      - 'DJANGO_ALLOWED_HOSTS=${DOMAIN}'
      - 'DJANGO_CSRF_TRUSTED_ORIGINS=${DJANGO_CSRF_TRUSTED_ORIGINS}'
      - 'DB_BACKEND=mysql'
      - 'MYSQL_HOST=db'
      - 'MYSQL_DATABASE=${MYSQL_DATABASE}'
      - 'MYSQL_USER=${MYSQL_USER}'
      - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
      - 'MYSQL_PORT=3306'
      - 'NADOOIT__API_KEY=${NADOOIT__API_KEY}'
      - 'NADOOIT__USER_CODE=${NADOOIT__USER_CODE}'
      - 'CELERY_BROKER_URL=redis://redis:6379/0'
    networks:
      - app_network
    depends_on:
      - redis
      - db

  redis:
    image: 'redis:latest'
    container_name: 'redis'
    hostname: 'redis'
    networks:
      - app_network

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: sh -c "python -m celery -A nadooit worker --loglevel=info"
    volumes:
      - ./app:/app
      - ./data/web:/vol/web
    environment:
      - 'DJANGO_DEBUG=${DJANGO_DEBUG}'
      - 'OPENAI_API_KEY=${OPENAI_API_KEY}'
      - 'DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}'
      - 'DJANGO_ALLOWED_HOSTS=${DOMAIN}'
      - 'DJANGO_CSRF_TRUSTED_ORIGINS=${DJANGO_CSRF_TRUSTED_ORIGINS}'
      - 'DB_BACKEND=mysql'
      - 'MYSQL_HOST=db'
      - 'MYSQL_DATABASE=${MYSQL_DATABASE}'
      - 'MYSQL_USER=${MYSQL_USER}'
      - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
      - 'MYSQL_PORT=3306'
      - 'NADOOIT__API_KEY=${NADOOIT__API_KEY}'
      - 'NADOOIT__USER_CODE=${NADOOIT__USER_CODE}'
      - 'CELERY_BROKER_URL=redis://redis:6379/0'
    networks:
      - app_network
    depends_on:
      - redis
      - db

  db:
    image: mysql:8.0.36
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - app_network

volumes:
  db_data:
