version: '3.8'

services:
  test:
    image: python:3.10-slim
    working_dir: /workspace/app
    volumes:
      - .:/workspace
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: >-
      sh -lc "
      apt-get update && apt-get install -y --no-install-recommends git && rm -rf /var/lib/apt/lists/* &&
      python -m pip install --upgrade pip &&
      pip install -r /workspace/requirements-dev.txt &&
      pytest -vv --cov=. --cov-config=.coveragerc --cov-report=term-missing:skip-covered --cov-report=xml:/workspace/coverage.xml
      "
