networks:
  app_network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev-Windows
    user: root
    command: >
      sh -c "
      set -ex;
      python -V;
      python -c 'import django; import sys; sys.stdout.write(django.get_version())'; echo;
      python manage.py check -v2;
      cp /app/cert.cer /tmp/cert.cer && cp /app/key.pem /tmp/key.pem;
      chmod 600 /tmp/cert.cer /tmp/key.pem 2>/dev/null || true;
      python manage.py makemigrations;
      python manage.py migrate;
      python manage.py import_templates;
      python manage.py import_section_orders;
      python manage.py collectstatic --noinput;
      python manage.py runsslserver 0.0.0.0:8000 --noreload --certificate /tmp/cert.cer --key /tmp/key.pem
      "
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - ./data/web:/vol/web
      - ./app/db:/app/db
    environment:
      - 'DJANGO_DEBUG=${DJANGO_DEBUG:-1}'
      - 'PYTHONUNBUFFERED=1'
      - 'PYTHONDONTWRITEBYTECODE=1'
      - 'OPENAI_API_KEY=${OPENAI_API_KEY}'
      - 'DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}'
      - 'DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS:-localhost,127.0.0.1,0.0.0.0,[::1]}'
      - 'DJANGO_CSRF_TRUSTED_ORIGINS=${DJANGO_CSRF_TRUSTED_ORIGINS:-https://localhost,https://127.0.0.1,https://0.0.0.0,https://[::1]}'
      - 'NADOOIT__API_KEY=${NADOOIT__API_KEY}'
      - 'NADOOIT__USER_CODE=${NADOOIT__USER_CODE}'
      - 'CELERY_BROKER_URL=redis://redis:6379/0'
    networks:
      - app_network
    depends_on:
      - redis
  redis:
    image: 'redis:latest'
    container_name: 'redis'
    hostname: 'redis'
    networks:
      - app_network
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile-dev-Windows
    user: root
    command: sh -c "python -m celery -A nadooit worker --loglevel=info"
    volumes:
      - ./app:/app
      - ./data/web:/vol/web
      - ./app/db:/app/db
    environment:
      - 'DJANGO_DEBUG=${DJANGO_DEBUG}'
      - 'OPENAI_API_KEY=${OPENAI_API_KEY}'
      - 'DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}'
      - 'DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}'
      - 'DJANGO_CSRF_TRUSTED_ORIGINS=${DJANGO_CSRF_TRUSTED_ORIGINS}'
      - 'NADOOIT__API_KEY=${NADOOIT__API_KEY}'
      - 'NADOOIT__USER_CODE=${NADOOIT__USER_CODE}'
      - 'CELERY_BROKER_URL=redis://redis:6379/0'
    networks:
      - app_network
    depends_on:
      - redis
