networks:
  app_network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev-Mac
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py import_templates && python manage.py import_section_orders && python manage.py collectstatic --noinput && python manage.py runserver_plus 0.0.0.0:8000 --cert-file cert.cer --key-file key.pem --insecure"
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - ./data/web:/vol/web
      - ./app/db:/app/db
    environment:
      - 'DJANGO_DEBUG=${DJANGO_DEBUG}'
      - 'OPENAI_API_KEY=${OPENAI_API_KEY}'
      - 'DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}'
      - 'DJANGO_ALLOWED_HOSTS=${DOMAIN}'
      - 'DJANGO_CSRF_TRUSTED_ORIGINS=${DJANGO_CSRF_TRUSTED_ORIGINS}'
      - 'NADOOIT__API_KEY=${NADOOIT__API_KEY}'
      - 'NADOOIT__USER_CODE=${NADOOIT__USER_CODE}'
      - 'CELERY_BROKER_URL=redis://redis:6379/0'
    networks:
      - app_network
    depends_on:
      - redis
  redis:
    image: 'redis:latest'
    container_name: 'redis'
    hostname: 'redis'
    networks:
      - app_network
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile-dev-Mac
    command: sh -c "python -m celery -A nadooit worker --loglevel=info"
    volumes:
      - ./app:/app
      - ./data/web:/vol/web
      - ./app/db:/app/db
    environment:
      - 'DJANGO_DEBUG=${DJANGO_DEBUG}'
      - 'OPENAI_API_KEY=${OPENAI_API_KEY}'
      - 'DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}'
      - 'DJANGO_ALLOWED_HOSTS=${DOMAIN}'
      - 'DJANGO_CSRF_TRUSTED_ORIGINS=${DJANGO_CSRF_TRUSTED_ORIGINS}'
      - 'NADOOIT__API_KEY=${NADOOIT__API_KEY}'
      - 'NADOOIT__USER_CODE=${NADOOIT__USER_CODE}'
      - 'CELERY_BROKER_URL=redis://redis:6379/0'
    networks:
      - app_network
    depends_on:
      - redis
