# Generated by Django 4.1.9 on 2023-07-05 14:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nadooit_crm', '0001_initial'),
        ('bot_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nadooit_crm.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('all_members_are_administrators', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('is_bot', models.BooleanField()),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('language_code', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'TelegramUser',
                'verbose_name_plural': 'TelegramUsers',
            },
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('file_id', models.CharField(max_length=100)),
                ('file_unique_id', models.CharField(max_length=100)),
                ('file_size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VoiceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='voice_files/')),
                ('voice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot_management.voice')),
            ],
        ),
        migrations.CreateModel(
            name='BotPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('facebook', 'Facebook Messenger'), ('whatsapp', 'WhatsApp')], max_length=50)),
                ('bot_register_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('access_token', models.CharField(max_length=100)),
                ('secret_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_management.bot')),
            ],
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('bot_platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_management.botplatform')),
            ],
        ),
    ]
