# Generated by Django 4.1.9 on 2023-06-12 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot_management", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="botplatform",
            name="api_key",
        ),
        migrations.RemoveField(
            model_name="botplatform",
            name="secret_url",
        ),
    ]
