# Generated by Django 4.1.9 on 2023-06-12 13:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0002_remove_botplatform_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botplatform',
            name='api_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='botplatform',
            name='secret_url',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
