# Generated by Django 4.1.9 on 2023-06-17 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "bot_management",
            "0010_chat_user_message_update_id_alter_message_voice_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
    ]
