# Generated by Django 4.1.9 on 2023-06-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_management", "0011_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="reply_markup",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
