# Generated by Django 4.1.9 on 2023-06-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_management", "0013_message_parse_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="botplatform",
            name="phone_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
