# Generated by Django 4.1.9 on 2023-07-01 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0019_alter_photomessage_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botplatform',
            old_name='secret_url',
            new_name='bot_register_id',
        ),
    ]
