# Generated by Django 4.0.7 on 2022-08-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nadooit_crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='customers',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
