# Generated by Django 4.0.7 on 2022-08-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nadooit_crm', '0002_remove_employee_customers_remove_employee_user'),
        ('nadooit_time_account', '0002_alter_timeaccountemployee_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
