# Generated by Django 4.0.7 on 2022-08-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nadooit_program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nadooitprogram',
            name='program_dependencies',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
