# Generated by Django 4.1.9 on 2023-06-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("condition", models.CharField(max_length=100)),
                ("quantity_available", models.BigIntegerField()),
                ("minimum_quantity", models.BigIntegerField()),
                ("location", models.CharField(max_length=100)),
                ("delivery_options", models.TextField()),
                ("link", models.URLField()),
                ("img_link", models.URLField()),
            ],
        ),
    ]
