# Generated by Django 4.1.13 on 2024-03-02 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nadooit_crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condition', models.CharField(max_length=100)),
                ('quantity_available', models.BigIntegerField()),
                ('minimum_quantity', models.BigIntegerField()),
                ('location', models.CharField(max_length=100)),
                ('delivery_options', models.TextField()),
                ('link', models.URLField()),
                ('img_link', models.URLField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nadooit_crm.customer')),
            ],
        ),
    ]
