# Generated by Django 4.1.9 on 2023-06-14 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nadooit_crm", "0001_initial"),
        ("nadoo_erp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="nadooit_crm.customer",
            ),
        ),
    ]
