# Generated by Django 4.1.9 on 2023-07-08 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0001_initial'),
        ('nadooit_auth', '0003_delete_keymanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_management.telegramuser')),
            ],
        ),
    ]
