# Generated by Django 5.0.3 on 2024-03-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nadooit_program_ownership_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprogram',
            name='fixed_price_per_second',
            field=models.BooleanField(default=True),
        ),
    ]
