# Generated by Django 4.1.2 on 2022-10-25 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nadooit_program_ownership_system', '0002_nadooitcustomerprogrammanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nadooitcustomerprogrammanager',
            old_name='Employee',
            new_name='employee',
        ),
    ]
