# Generated by Django 4.1.2 on 2022-10-31 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "nadooit_program_ownership_system",
            "0008_customerprogrammanager_can_give_customerprogrammanager_role",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="customerprogrammanager",
            old_name="can_give_CustomerProgramManager_role",
            new_name="can_give_customerprogrammanager_role",
        ),
    ]
