# Generated by Django 4.1.2 on 2022-10-31 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nadooit_network', '0001_initial'),
        ('nadooit_program', '0001_initial'),
        ('nadooit_program_ownership_system', '0009_rename_can_give_customerprogrammanager_role_customerprogrammanager_can_give_customerprogrammanager_r'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NadooitProgramShare',
            new_name='ProgramShare',
        ),
    ]
