# Generated by Django 4.1.2 on 2022-11-07 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "nadooit_program_ownership_system",
            "0013_rename_can_give_customerprogrammanager_role_customerprogrammanager_can_give_manager_role",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomerProgramManager",
        ),
    ]
