# Generated by Django 4.1.3 on 2022-11-19 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nadooit_program_ownership_system", "0014_delete_customerprogrammanager"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customerprogram",
            old_name="price_per_second_in_cent",
            new_name="price_per_second",
        ),
    ]
