# Generated by Django 4.1.3 on 2022-11-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nadooit_program_ownership_system', '0016_customerprogram_price_per_second_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprogram',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
