# Generated by Django 4.1.13 on 2024-03-02 19:41

from django.db import migrations, models
import django.db.models.deletion
import nadooit_website.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('fast_and_engaged', 'Fast and Engaged'), ('fast_and_not_engaged', 'Fast and Not Engaged'), ('slow_and_engaged', 'Slow and Engaged'), ('slow_and_not_engaged', 'Slow and Not Engaged')], max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('successful_sessions', models.IntegerField(default=0)),
                ('total_sessions', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('html', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('html', models.TextField()),
                ('greeting_sction', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(to='nadooit_website.category')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nadooit_website.file')),
            ],
        ),
        migrations.CreateModel(
            name='Section_Order',
            fields=[
                ('section_order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_order_date', models.DateTimeField(auto_now_add=True)),
                ('plugins', models.ManyToManyField(to='nadooit_website.plugin')),
            ],
        ),
        migrations.CreateModel(
            name='Section_Transition',
            fields=[
                ('section_transition_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_1_id', models.UUIDField()),
                ('section_2_id', models.UUIDField()),
                ('transition_percentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_start_time', models.DateTimeField(auto_now_add=True)),
                ('session_duration', models.IntegerField(default=0)),
                ('total_interaction_time', models.FloatField(default=0)),
                ('session_clicked_on_appointment_form', models.BooleanField(default=False)),
                ('session_score', models.IntegerField(default=0)),
                ('is_bot_visit', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('fast', 'Fast'), ('slow', 'Slow')], default='fast', max_length=255)),
                ('variant', models.CharField(choices=[('control', 'Control'), ('experimental', 'Experimental')], default='control', max_length=255)),
                ('experiment_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nadooit_website.experimentgroup')),
                ('session_section_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nadooit_website.section_order')),
                ('shown_sections', models.ManyToManyField(blank=True, to='nadooit_website.section')),
            ],
            options={
                'ordering': ['-session_start_time'],
            },
        ),
        migrations.CreateModel(
            name='Signals_Option',
            fields=[
                ('signal_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signal_date', models.DateTimeField(auto_now_add=True)),
                ('signal_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('preview_image', models.ImageField(upload_to='video_previews/')),
                ('reprocess_video', models.BooleanField(default=False)),
                ('original_file', models.FileField(upload_to='original_videos/')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('site', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VideoResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.PositiveIntegerField()),
                ('video_file', models.FileField(upload_to='videos/')),
                ('hls_playlist_file', models.FileField(blank=True, max_length=500, null=True, upload_to=nadooit_website.models.hls_upload_to)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='nadooit_website.video')),
            ],
        ),
        migrations.CreateModel(
            name='Session_Signal',
            fields=[
                ('session_signal_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_signal_date', models.DateTimeField(auto_now_add=True)),
                ('session_signal_type', models.CharField(max_length=200)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nadooit_website.section')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nadooit_website.session')),
            ],
        ),
        migrations.CreateModel(
            name='SectionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('experiment_group', models.IntegerField(choices=[(0, 'Control'), (1, 'Experimental')], default=0)),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nadooit_website.section')),
            ],
        ),
        migrations.CreateModel(
            name='Section_Transition_Test',
            fields=[
                ('section_test_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_test_date', models.DateTimeField(auto_now_add=True)),
                ('section_was_pased', models.BooleanField(default=False)),
                ('section_transition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nadooit_website.section_transition')),
            ],
        ),
        migrations.CreateModel(
            name='Section_Order_Sections_Through_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nadooit_website.section')),
                ('section_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nadooit_website.section_order')),
            ],
            options={
                'ordering': ('section_order', 'order'),
            },
        ),
        migrations.AddField(
            model_name='section_order',
            name='sections',
            field=models.ManyToManyField(through='nadooit_website.Section_Order_Sections_Through_Model', to='nadooit_website.section'),
        ),
        migrations.CreateModel(
            name='Section_Competition',
            fields=[
                ('section_competition_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_competition_date', models.DateTimeField(auto_now_add=True)),
                ('section_1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nadooit_website.section')),
                ('section_transition_tests', models.ManyToManyField(to='nadooit_website.section_transition_test')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='signal_options',
            field=models.ManyToManyField(blank=True, to='nadooit_website.signals_option'),
        ),
        migrations.AddField(
            model_name='section',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nadooit_website.video'),
        ),
        migrations.AddField(
            model_name='experimentgroup',
            name='section_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nadooit_website.section_order'),
        ),
    ]
