# Generated by Django 4.1.3 on 2023-03-31 15:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("nadooit_website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "section_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("section_name", models.CharField(max_length=200)),
                ("section_html", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Section_Transition_Test",
            fields=[
                (
                    "section_test_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("section_test_date", models.DateTimeField(auto_now_add=True)),
                ("section_test_time", models.DateTimeField(auto_now_add=True)),
                ("section_1_id", models.UUIDField()),
                ("section_2_id", models.UUIDField()),
                ("transition_percentage", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "session_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_start_time", models.DateTimeField(auto_now_add=True)),
                ("session_end_time", models.DateTimeField(auto_now_add=True)),
                ("session_score", models.IntegerField()),
                ("session_duration", models.IntegerField()),
                ("session_section_order", models.CharField(max_length=200)),
                ("session_made_appointment", models.BooleanField(default=False)),
            ],
        ),
    ]
