# Generated by Django 4.1.3 on 2023-04-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "nadooit_website",
            "0005_section_order_section_order_sections_through_model_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="section_html",
            field=models.TextField(),
        ),
    ]
