# Generated by Django 4.1.3 on 2023-04-04 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nadooit_website", "0006_alter_section_section_html"),
    ]

    operations = [
        migrations.RenameField(
            model_name="session",
            old_name="session_made_appointment",
            new_name="session_clicked_on_appointment_form",
        ),
    ]
