# Generated by Django 4.1.3 on 2023-04-04 17:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "nadooit_website",
            "0007_rename_session_made_appointment_session_session_clicked_on_appointment_form",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Signals_Options",
            fields=[
                (
                    "signal_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("signal_date", models.DateTimeField(auto_now_add=True)),
                ("signal_type", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="section",
            name="signal_options",
            field=models.ManyToManyField(
                blank=True, to="nadooit_website.signals_options"
            ),
        ),
    ]
