# Generated by Django 4.1.3 on 2023-04-04 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nadooit_website", "0009_session_signals"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Signals_Options",
            new_name="Signals_Option",
        ),
    ]
