# Generated by Django 4.1.3 on 2023-04-07 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nadooit_website", "0010_rename_signals_options_signals_option"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Session_Signals",
        ),
    ]
