# Generated by Django 4.1.3 on 2023-04-07 10:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("nadooit_website", "0011_delete_session_signals"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session_Signals",
            fields=[
                (
                    "session_signal_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_signal_date", models.DateTimeField(auto_now_add=True)),
                ("session_signal_type", models.CharField(max_length=200)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nadooit_website.section",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="session",
            name="session_signals",
            field=models.ManyToManyField(
                blank=True, to="nadooit_website.session_signals"
            ),
        ),
    ]
