# Generated by Django 4.1.3 on 2023-04-10 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nadooit_website", "0014_delete_question_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="shown_sections",
            field=models.ManyToManyField(blank=True, to="nadooit_website.section"),
        ),
        migrations.CreateModel(
            name="SectionScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(default=0)),
                (
                    "section",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nadooit_website.section",
                    ),
                ),
            ],
        ),
    ]
