# Generated by Django 4.1.3 on 2023-04-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nadooit_website", "0015_session_shown_sections_sectionscore"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExperimentGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="section",
            name="category",
            field=models.CharField(
                choices=[("fast", "Fast"), ("slow", "Slow")],
                default="fast",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="sectionscore",
            name="experiment_group",
            field=models.IntegerField(
                choices=[(0, "Control"), (1, "Experimental")], default=0
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="category",
            field=models.CharField(
                choices=[("fast", "Fast"), ("slow", "Slow")],
                default="fast",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="session_signals",
            name="total_interaction_time",
            field=models.FloatField(default=0),
        ),
    ]
