# Generated by Django 4.1.3 on 2023-04-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nadooit_website", "0016_experimentgroup_section_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="session_score",
            field=models.IntegerField(default=0),
        ),
    ]
