# Generated by Django 4.1.3 on 2023-04-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "nadooit_website",
            "0018_remove_session_signals_total_interaction_time_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="variant",
            field=models.CharField(
                choices=[("control", "Control"), ("experimental", "Experimental")],
                default="control",
                max_length=255,
            ),
        ),
    ]
