# Generated by Django 4.1.3 on 2023-04-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nadooit_website", "0019_session_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="plugin",
            field=models.BooleanField(default=False),
        ),
    ]
