# Generated by Django 4.1.3 on 2023-04-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nadooit_website", "0020_section_plugin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("fast_and_engaged", "Fast and Engaged"),
                            ("fast_and_not_engaged", "Fast and Not Engaged"),
                            ("slow_and_engaged", "Slow and Engaged"),
                            ("slow_and_not_engaged", "Slow and Not Engaged"),
                        ],
                        max_length=255,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="section",
            name="category",
        ),
        migrations.AddField(
            model_name="section",
            name="categories",
            field=models.ManyToManyField(to="nadooit_website.category"),
        ),
    ]
