# Generated by Django 4.1.3 on 2023-04-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nadooit_website", "0024_session_signals_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="greeting_sction",
            field=models.BooleanField(default=False),
        ),
    ]
