# Generated by Django 4.1.3 on 2023-04-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nadooit_website", "0025_section_greeting_sction"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plugins",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plugin_name", models.CharField(max_length=200)),
                ("plugin_html", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="section_order",
            name="plugins",
            field=models.ManyToManyField(to="nadooit_website.plugins"),
        ),
    ]
