# Generated by Django 4.1.3 on 2023-04-17 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nadooit_website", "0026_plugins_section_order_plugins"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Plugins",
            new_name="Plugin",
        ),
    ]
