# Generated by Django 4.1.3 on 2023-04-17 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nadooit_website", "0027_rename_plugins_plugin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="section",
            name="plugin",
        ),
    ]
