# Generated by Django 4.1.3 on 2023-04-17 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nadooit_website", "0028_remove_section_plugin"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plugin",
            old_name="plugin_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="section",
            old_name="section_name",
            new_name="name",
        ),
    ]
