# Generated by Django 4.1.3 on 2023-04-17 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nadooit_website", "0030_rename_plugin_html_plugin_html_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Session_Signals",
            new_name="Session_Signal",
        ),
    ]
