# Generated by Django 4.1.3 on 2023-04-19 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nadooit_website", "0031_rename_session_signals_session_signal"),
    ]

    operations = [
        migrations.AddField(
            model_name="experimentgroup",
            name="section_order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="nadooit_website.section_order",
            ),
        ),
        migrations.AddField(
            model_name="experimentgroup",
            name="successful_sessions",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="experimentgroup",
            name="total_sessions",
            field=models.IntegerField(default=0),
        ),
    ]
