# Generated by Django 4.1.3 on 2023-04-24 09:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("nadooit_website", "0032_experimentgroup_section_order_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "video_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("video_file", models.FileField(upload_to="videos/")),
                ("preview_image", models.ImageField(upload_to="video_previews/")),
            ],
        ),
        migrations.AddField(
            model_name="section",
            name="video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nadooit_website.video",
            ),
        ),
    ]
