# Generated by Django 4.1.3 on 2023-04-25 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nadooit_website", "0034_rename_video_id_video_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="video_file",
        ),
        migrations.CreateModel(
            name="VideoResolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resolution", models.PositiveIntegerField()),
                ("video_file", models.FileField(upload_to="videos/")),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resolutions",
                        to="nadooit_website.video",
                    ),
                ),
            ],
        ),
    ]
