# Generated by Django 4.1.3 on 2023-04-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nadooit_website", "0036_video_original_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoresolution",
            name="hls_playlist_file",
            field=models.FileField(default="", upload_to="hls_playlists/"),
            preserve_default=False,
        ),
    ]
