# Generated by Django 4.1.3 on 2023-05-02 13:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("nadooit_website", "0038_alter_video_original_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "file_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("file", models.FileField(upload_to="uploads/")),
            ],
        ),
        migrations.AddField(
            model_name="section",
            name="file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nadooit_website.file",
            ),
        ),
    ]
