# Generated by Django 4.1.3 on 2023-05-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nadooit_website", "0040_onlinevideomeetingrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="onlinevideomeetingrequest",
            name="room_name",
            field=models.CharField(default=1, max_length=36, unique=True),
            preserve_default=False,
        ),
    ]
