# Generated by Django 4.1.9 on 2023-05-19 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nadooit_website', '0040_session_is_bot_visit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-session_start_time']},
        ),
    ]
