# Generated by Django 4.1.9 on 2023-06-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nadooit_website', '0042_video_reprocess_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='original_file',
            field=models.FileField(upload_to='original_videos/'),
        ),
    ]
