# Generated by Django 4.1.9 on 2023-06-04 10:29

from django.db import migrations, models
import nadooit_website.models


class Migration(migrations.Migration):

    dependencies = [
        ('nadooit_website', '0043_alter_video_original_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoresolution',
            name='hls_playlist_file',
            field=models.FileField(upload_to=nadooit_website.models.hls_upload_to),
        ),
    ]
