# Generated by Django on 2025-08-10
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nadooit_website", "0045_alter_videoresolution_hls_playlist_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentPage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=150, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("html", models.TextField(help_text="Raw HTML body. Rendered as-is for trusted content.")),
                ("css", models.TextField(blank=True, default="", help_text="Optional CSS to apply to this page.")),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
