# Generated by Cascade
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nadooit_website", "0046_contentpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentpage",
            name="js",
            field=models.TextField(blank=True, default="", help_text="Optional JavaScript to run on this page."),
        ),
    ]
