# Generated by Django 4.2.23 on 2025-08-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nadooit_website', '0047_contentpage_js'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
