# Generated by Django 4.0.7 on 2022-08-25 15:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nadooit_program', '0002_nadooitprogram_program_dependencies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('process_trigger_events', models.CharField(max_length=255)),
                ('process_subscriptions', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('list_of_nadooit_programs', models.ManyToManyField(to='nadooit_program.nadooitprogram')),
            ],
        ),
    ]
