# Generated by Django 4.0.7 on 2022-08-25 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nadooit_crm', '0001_initial'),
        ('nadooit_workflow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='process_subscriptions',
        ),
        migrations.RemoveField(
            model_name='process',
            name='process_trigger_events',
        ),
        migrations.AddField(
            model_name='process',
            name='customer',
            field=models.ForeignKey(default='acc3c9cc-b414-443f-94e3-74e6e58d121a', on_delete=django.db.models.deletion.CASCADE, to='nadooit_crm.customer'),
            preserve_default=False,
        ),
    ]
