# Generated by Django 4.0.7 on 2022-08-25 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nadooit_workflow', '0002_remove_process_process_subscriptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='tiggers_process',
            field=models.ManyToManyField(blank=True, to='nadooit_workflow.process'),
        ),
        migrations.AddField(
            model_name='process',
            name='trigger_process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nadooit_workflow.process'),
        ),
    ]
