# Generated by Django 4.0.7 on 2022-08-25 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nadooit_program', '0001_initial'),
        ('nadooit_program_ownership_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nadooitcustomerprogram',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nadooit_program.nadooitprogram'),
        ),
        migrations.AlterField(
            model_name='nadooitprogramshare',
            name='share_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nadooit_program.nadooitprogram'),
        ),
        migrations.DeleteModel(
            name='NadooitProgram',
        ),
    ]
