# Generated by Django 4.1.13 on 2024-03-02 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nadooit_program_ownership_system', '0001_initial'),
        ('nadooit_api_executions_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprogramexecution',
            name='customer_program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nadooit_program_ownership_system.customerprogram'),
        ),
    ]
