# Generated by Django 4.1.2 on 2022-10-25 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nadooit_api_executions_system', '0003_customerprogramexecutionmanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprogramexecutionmanager',
            old_name='Employee',
            new_name='employee',
        ),
    ]
