# Generated by Django 4.1.2 on 2022-10-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "nadooit_hr",
            "0005_customermanager_list_of_employees_the_manager_has_given_the_role_to_and_more",
        ),
        (
            "nadooit_api_executions_system",
            "0006_rename_customers_the_manager_is_responsible_for_customerprogramexecutionmanager_list_of_customers_th",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprogramexecutionmanager",
            name="list_of_employees_the_manager_has_given_the_role_to",
            field=models.ManyToManyField(
                blank=True,
                related_name="list_of_employees_the_customer_program_execution_manager_has_given_the_role_to",
                to="nadooit_hr.employee",
            ),
        ),
    ]
