# Generated by Django 4.1.3 on 2022-11-19 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nadooit_api_executions_system', '0013_alter_customerprogramexecution_price_per_second_in_cent_at_the_time_of_execution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprogramexecution',
            old_name='price_per_second_in_cent_at_the_time_of_execution',
            new_name='price_per_second_at_the_time_of_execution',
        ),
        migrations.RenameField(
            model_name='customerprogramexecution',
            old_name='price_per_second_in_cent_at_the_time_of_execution_currency',
            new_name='price_per_second_at_the_time_of_execution_currency',
        ),
    ]
