# Generated by Django 4.1.13 on 2024-03-02 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nadooit_crm', '0001_initial'),
        ('nadooit_hr', '0001_initial'),
        ('nadooit_api_key', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NadooitApiKeyManager',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nadooit_hr.employee')),
                ('can_create_api_key', models.BooleanField(default=False)),
                ('can_delete_api_key', models.BooleanField(default=False)),
                ('can_give_manager_role', models.BooleanField(default=False)),
                ('list_of_customers_the_manager_is_responsible_for', models.ManyToManyField(blank=True, to='nadooit_crm.customer')),
                ('list_of_employees_the_manager_has_given_the_role_to', models.ManyToManyField(blank=True, related_name='list_of_employees_the_api_key_manager_has_given_the_role_to', to='nadooit_hr.employee')),
            ],
        ),
        migrations.AddField(
            model_name='nadooitapikey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
