# Generated by Django 4.1.2 on 2022-10-25 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nadooit_api_key', '0005_nadooitapikeymanager_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nadooitapikeymanager',
            name='employee',
        ),
    ]
