# Generated by Django 4.1.2 on 2022-10-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "nadooit_hr",
            "0004_rename_customers_the_manager_is_responsible_for_employeemanager_list_of_customers_the_manager_is_res",
        ),
        (
            "nadooit_api_key",
            "0010_rename_customers_the_manager_is_responsible_for_nadooitapikeymanager_list_of_customers_the_manager_i",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="nadooitapikeymanager",
            name="list_of_employees_the_manager_has_given_the_role_to",
            field=models.ManyToManyField(
                blank=True,
                related_name="list_of_employees_the_api_key_manager_has_given_the_role_to",
                to="nadooit_hr.employee",
            ),
        ),
    ]
