# Generated by Django 4.1.2 on 2022-11-04 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "nadooit_api_key",
            "0011_nadooitapikeymanager_list_of_employees_the_manager_has_given_the_role_to",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="nadooitapikeymanager",
            old_name="can_give_ApiKeyManager_role",
            new_name="can_give_manager_role",
        ),
    ]
