# Generated by Django 4.0.7 on 2022-08-24 19:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nadooit_crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_balance_in_seconds', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeAccountEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nadooit_crm.customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nadooit_crm.employee')),
                ('time_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nadooit_time_account.timeaccount')),
            ],
        ),
        migrations.CreateModel(
            name='WorkTimeAccountEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_time', models.TimeField(blank=True, null=True)),
                ('work_date', models.DateField(blank=True, null=True)),
                ('entry_trype', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], default='IN', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nadooit_time_account.timeaccountemployee')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerNadooitTimeAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nadooit_crm.customer')),
                ('time_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nadooit_time_account.timeaccount')),
            ],
        ),
    ]
