# Generated by Django 4.1.13 on 2024-03-02 19:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nadooit_crm', '0001_initial'),
        ('nadooit_hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTimeAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nadooit_crm.customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nadooit_hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='TimeAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_balance_in_seconds', models.BigIntegerField(blank=True, default=0, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkTimeAccountEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_time', models.TimeField(blank=True, null=True)),
                ('work_date', models.DateField(blank=True, null=True)),
                ('entry_trype', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], default='IN', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_time_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nadooit_time_account.employeetimeaccount')),
            ],
        ),
        migrations.AddField(
            model_name='employeetimeaccount',
            name='time_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nadooit_time_account.timeaccount'),
        ),
        migrations.CreateModel(
            name='CustomerTimeAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nadooit_crm.customer')),
                ('time_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nadooit_time_account.timeaccount')),
            ],
        ),
    ]
