# Generated by Django 4.1.2 on 2022-10-21 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nadooit_crm", "0001_initial"),
        (
            "nadooit_time_account",
            "0002_rename_timeaccountemployee_employeetimeaccount_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CustomerNadooitTimeAccount",
            new_name="CustomerTimeAccount",
        ),
    ]
