# Generated by Django 4.1.2 on 2022-10-21 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nadooit_time_account', '0003_rename_customernadooittimeaccount_customertimeaccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worktimeaccountentry',
            old_name='time_account',
            new_name='employee_time_account',
        ),
    ]
