# Generated by Django 4.1.2 on 2022-10-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nadooit_time_account', '0004_rename_time_account_worktimeaccountentry_employee_time_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeaccount',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
