# Generated by Django 4.1.2 on 2022-10-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nadooit_time_account", "0006_customertimeaccount_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customertimeaccount",
            name="name",
            field=models.CharField(default="FIXME", max_length=255),
            preserve_default=False,
        ),
    ]
