# Generated by Django 4.1.2 on 2022-10-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nadooit_time_account', '0009_timeaccountmanager_customers_the_manager_is_responsible_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='timeaccountmanager',
            name='can_create_time_accounts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeaccountmanager',
            name='can_delete_api_key',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeaccountmanager',
            name='can_give_ApiKeyManager_role',
            field=models.BooleanField(default=False),
        ),
    ]
