# Generated by Django 4.0.7 on 2022-08-26 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nadooit_program_ownership_system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NadooitInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('money', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('list_of_nadooit_program_ownership_shares', models.ManyToManyField(blank=True, to='nadooit_program_ownership_system.nadooitprogramshare')),
            ],
        ),
        migrations.CreateModel(
            name='NadooitNetworkMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nadooit_network.nadooitinventory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NadooitNetworkGuildMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guild_role', models.CharField(choices=[('MEMBER', 'MEMBER'), ('MODERATOR', 'MODERATOR'), ('ADMIN', 'ADMIN')], default='MEMBER', max_length=20)),
                ('nadooit_network_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nadooit_network.nadooitnetworkmember')),
            ],
        ),
        migrations.CreateModel(
            name='NadooitNetworkGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='nadooit_network.nadooitnetworkmember')),
                ('members', models.ManyToManyField(blank=True, to='nadooit_network.nadooitnetworkmember')),
            ],
        ),
        migrations.CreateModel(
            name='NadooitNetworkFriendslist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('friend_list', models.ManyToManyField(related_name='friend_list', to='nadooit_network.nadooitnetworkmember')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nadooit_network.nadooitnetworkmember')),
            ],
        ),
        migrations.CreateModel(
            name='NadooitGuildBank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guild_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nadooit_network.nadooitinventory')),
            ],
        ),
        migrations.CreateModel(
            name='NadooitGuild',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guild_logo', models.ImageField(blank=True, null=True, upload_to='guild_logo')),
                ('member_list', models.ManyToManyField(blank=True, to='nadooit_network.nadooitnetworkguildmember')),
            ],
        ),
    ]
