# Generated by Django 4.1.2 on 2022-10-25 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nadooit_crm", "0001_initial"),
        (
            "nadooit_hr",
            "0002_rename_customers_employee_customers_the_employee_works_for",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customers_the_manager_is_responsible_for",
                    models.ManyToManyField(blank=True, to="nadooit_crm.customer"),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nadooit_hr.employee",
                    ),
                ),
            ],
        ),
    ]
