# Generated by Django 4.1.2 on 2022-11-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nadooit_hr', '0010_employeecontract_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecontract',
            name='deactivation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
