# Generated by Django 4.1.2 on 2022-11-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nadooit_hr", "0011_employeecontract_deactivation_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeemanager",
            name="can_delete_employee",
            field=models.BooleanField(default=False),
        ),
    ]
