# Generated by Django 4.1.2 on 2022-11-04 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nadooit_hr', '0012_employeemanager_can_delete_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeemanager',
            old_name='can_give_EmployeeManager_role',
            new_name='can_give_manager_role',
        ),
    ]
