# Generated by Django 4.1.2 on 2022-11-05 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "nadooit_hr",
            "0015_rename_can_add_new_employees_employeemanager_can_add_new_employee",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeemanager",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="nadooit_hr.employee"
            ),
        ),
    ]
