# Generated by Django 4.1.2 on 2022-11-05 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nadooit_hr", "0016_alter_employeemanager_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeemanager",
            name="employee",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="nadooit_hr.employee"
            ),
        ),
    ]
