# Generated by Django 4.1.2 on 2022-11-05 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nadooit_hr', '0018_employeemanagercontract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemanagercontract',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nadooit_hr.employeecontract'),
        ),
    ]
