# Generated by Django 4.1.2 on 2022-11-06 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nadooit_hr', '0019_alter_employeemanagercontract_contract'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeManager',
        ),
    ]
