# Generated by Django 4.1.2 on 2022-11-06 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nadooit_hr", "0020_delete_employeemanager"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerManagerContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_give_manager_role", models.BooleanField(default=False)),
                (
                    "contract",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nadooit_hr.employeecontract",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerProgramManagerContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_create_customer_program", models.BooleanField(default=False)),
                ("can_delete_customer_program", models.BooleanField(default=False)),
                ("can_give_manager_role", models.BooleanField(default=False)),
                (
                    "contract",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nadooit_hr.employeecontract",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="CustomerManager",
        ),
    ]
