# Generated by Django 4.1.3 on 2023-05-09 10:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("nadooit_hr", "0025_employeemanagercontract_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallCenterWorkerContract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active_worker", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee_contract",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nadooit_hr.employeecontract",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CallCenterManagerContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_create_worker_contract", models.BooleanField(default=False)),
                ("can_deactivate_worker_contract", models.BooleanField(default=False)),
                ("can_promote_to_manager", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contract",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nadooit_hr.employeecontract",
                    ),
                ),
            ],
        ),
    ]
