# This file is auto-generated by NADOO Launchpad.
# It contains the nginx location blocks for FastAPI microservices.


# Configuration for chat_service
location /api/chat_service/ {
    proxy_pass http://chat_service:8001/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}
